### ISSUE TITLE
some parameters doesn't move to cuda when using GPU

### ISSUE THREAD

**Issue by Louis-Jin** [chanberg/atmt#2]
WIth Python 3.6 + Pytorch 1.3 + Cuda 10.1, reporting issue:

```
atmt\seq2seq\models\lstm.py, line 275, in forward, 
RuntimeError: Expected object of device type cuda but got device type cpu for argument #1 "self" in call to th_mm`
```

The **reason** is some parameters in LSTMDecoder hasn't been moved to cuda.

**To fix it:**
After initializing tgt_hidden_states and tgt_cell_states inside forward function of LSTMDecoder, add

```python
if self.layers[0].weight_ih.is_cuda:
      tgt_hidden_states = utils.move_to_cuda(tgt_hidden_states)
      tgt_cell_states = utils.move_to_cuda(tgt_cell_states)
```

**Comment by chanberg** [comment]
hi!
Thanks for reporting this and #1 .
As written in the first assignment, we advise you to run the code with Pytorch 0.4.1 and on CPU because we cannot give you access to a GPU. If you (or other students) have access and want to run it with another version of Pytorch feel free to do so and make these changes in your forked repository.

**Comment by Louis-Jin** [comment]
:) yes, just in case someone also wants to run on GPU. Making those two changes should be enough.

**Comment by SpielmannCode** [comment]
Were you able to use the models trained on cuda? We tried to fix it, but could not get the translate runing with models calculated on a GPU

**Comment by Louis-Jin** [comment]
Yes. translate.py also have issues regarding gpu, but there is not much need to fix it so I just let it run on cpu. One problem to do that is when loading model, args also got loaded(which has cuda set to True), so you can add args.cuda=False after utils.init_logging(args) in translate.py.

**Comment by SpielmannCode** [comment]
Thanks a Lot
